### PR TITLE
Do not require azavea.java role

### PR DESCRIPTION
**Pull request by lhoss**

### CODE REVIEW

**Comment by hectcastro** [comment]
Hey @lhoss, could you please explain this proposed change?

**Comment by lhoss** [comment]
hi!
I guess this change makes less sense for you(r company), but not for us (we setup JDK in a different way) , nor it seems for some other people (saw at least 2 other forks with commits to remove it).
Anyway, initially I wanted to only make a PR on my (remote)fork.
So you can simply ignore or close this PR.

I'm having some more useful contributions, pushed possibly today,
like allowing a different base folder (instead of /usr/lib) where the main spark gets installed.
Plus, another commit, even more useful (for many people) to also generate a spark-defaults.conf.
Will be happy to contribute back!

**Comment by hectcastro** [comment]
Thanks for the explanation, @lhoss.

**Comment by lhoss** [comment]
I forgot that this PR existed (indeed last Oct. it wasn't intentional) .. 
so I moved my comment done in https://github.com/azavea/ansible-spark/pull/10 here:
Would you mind (me) taking out the meta/dependency on your java role?
( ps: In our large cluster setup we don't use dependencies, but rather a composable 'full-setup.yml' playbook with includes that installs java, zk, mesos, hdfs, spark etc in diff. plays )

( so other users building on your role don't have to fork it, just to disable the dependency, to use another role, for ex. to get JDK8 support)

Unfort. ansible doesn't yet offer a feature to easily disable 'transient dependencies'.
I created an ansible feature request: ansible/ansible#13215 , but will probably take time to get it builtin (hopefully for v2.1)

**Comment by hectcastro** [comment]
I'm not entirely sure that we could support that because much of our Spark usage is setup to work with this dependency. The proposed solutions in #13215 make sense. I think we would want to keep the dependency and use an Ansible level feature like that to disable.

**Comment by lhoss** [comment]
OK AFAIK than for us the best solution is to have a deviant branch (just with the dependency removed), where I merge all other changes into (that I've done first in develop)

**Comment by lhoss** [comment]
fyi  finally a non breaking solution for this original idea (to be able to avoid the need for the role dependency): https://github.com/azavea/ansible-spark/pull/26

**Pull request closed without merging**
